production:
  adapter: mysql
  username:
  password:
  database:
development:
  adapter: mysql
  username:
  password:
  database:
test: &test
  adapter:  mysql
  username:
  password:
  database:
cucumber:
  <<: *test
